### ISSUE TITLE
Finalise finding data sources

### ISSUE THREAD

**Issue by Kallikrates** [Kallikrates/DSP_AT2#14]
This task is to finalise finding data sources for analysis. This includes facts, and hopefully associated dimension data. The product of this task is to provide the data ready for processing, including relevant keys.

**Comment by adrianciaff** [comment]
I found some data sources on Bitcoin being traded in multiple different local currencies. The source is from a popular peer to peer exchange called [localbitcoins](https://localbitcoins.com/). It shows how Bitcoin is being traded against different local currencies. This could be a good way to introduce more dimensions to our data.

**Comment by adrianciaff** [comment]
As discussed in the meeting. We have some data on trading volumes of different local currencies, @svetlana2113 noticed that there are some countries with increasing volume in recent months, so one suggestion is for us to try and understand why these countries in particular are experiencing a spike in trading volume compared to other countries. Some examples of reasons we discussed were things like **access to internet**, **technological progress**, etc. 
*The action item for this meeting is therefore to finalize the datasets we can get for examples listed above and clean up the repo so it is ready for processing by Sunday 10th.

**Comment by Kallikrates** [comment]
Data updated in repo. Closing.
