### ISSUE TITLE
Team Name Ideas

### ISSUE THREAD

**Issue by adrianciaff** [Kallikrates/DSP_AT2#16]
Hi everyone, as Werner mentioned in the meeting we need to think of a team name. I've just added something I thought of last night but please feel free to list any of your own suggestions below.

- 'Surge' an app or dashboard for spotting trends in trading volume.

**Comment by Kallikrates** [comment]
My contribution is Gamas-W6. It's an anagram using the first letters of our names (AAGMSW), plus 6 for our number. It's a little abstract though. It's not as good as Tom Riddle = Lord Voldemort.

**Comment by Kallikrates** [comment]
My contribution is Gamas-W6. It's an anagram using the first letters of our names (AAGMSW), plus 6 for our number. It's a little abstract though. It's not as good as Tom Marvolo Riddle = I am Lord Voldemort.

**Comment by Kallikrates** [comment]
Since no one's biting, I'll put in a couple: WAGS (AM). Random, but an anagram of our first names' first letters. Or Gamas-W6. Same, but with 6 representing out number.

**Comment by gwmdsi** [comment]
Given it's a collaboration assignment and out topic: GitCoin

**Comment by Kallikrates** [comment]
Hey @adrianciaff ...I've called the database etc. GitCoin, so I supposed that's it?

**Comment by adrianciaff** [comment]
Sounds good to me
