### ISSUE TITLE
Design GitHub process for committing/branching/merging code 

### ISSUE THREAD

**Issue by Kallikrates** [Kallikrates/DSP_AT2#2]
This will help us meet the requirement, ensure we don't all do things differently that may or may not work, and also be a good learning exercise. Duhita stated that it's to follow the 'workflow i showed in class' - so week 7. However for GitHub, this description is not complete. I've had a go at listing the steps below. The person that does this task should confirm/update the below.

It shouldn't need more than a one pager (or a diagram with short step descriptions) defining a workflow to:

1. Create repository (repo) on GitHub - Done.
2. Clone remote repo locally - all team members should have a local version of the repo.
3. Pull master branch from remote to local (every time you want to make changes, in case this has changed since the last pull).
3. Branch out file/code you want to work on.
4. Update file/code.
5. Commit changes to branch.
6. Push changed local code/data/documents up to the central repo for team member/s to review.
7. Compare and Pull Request on GitHub.
8. Create pull request for team to approve whether change can be merged to master branch.
9. Designated team member to review changes.
10. Merge pull request branch to main repo branch.

This can then be added to the report. This is to satisfy ‘Appropriateness of commits and branches to collaborate within a team using Git, adhering to one of the documented workflows’ and ‘Clarity and efficiency of content review and change negotiation using Pull Requests, and successful incorporation of individual changes into the team’s master branch.’ **Together these are worth 30% of the mark.**

**Comment by Kallikrates** [comment]
I found a good instruction video that takes you through the process. https://www.youtube.com/watch?v=MnUd31TvBoU

**Comment by Kallikrates** [comment]
Good video to learn how to clone locally: https://www.youtube.com/watch?v=O72FWNeO-xY&t=1s
Good video to learn Git/GitHub collaboration workflow. https://www.youtube.com/watch?v=MnUd31TvBoU

**Comment by gwmdsi** [comment]
Done
